# Generated by Django 6.0.7 on 2026-09-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='tasks.task', verbose_name='Depende da tarefa')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='tasks.task', verbose_name='Tarefa dependente')),
            ],
            options={
                'verbose_name': 'Dependência',
                'verbose_name_plural': 'Dependências',
                'ordering': ['depends_on__title'],
                'constraints': [models.UniqueConstraint(fields=('task', 'depends_on'), name='unique_task_dependency'), models.CheckConstraint(condition=models.Q(('task', models.F('depends_on')), _negated=True), name='prevent_self_dependency')],
            },
        ),
    ]
